version     = "0.0.0"
author      = "Andre von Houck"
description = "An nostaligic PHP BB style simple forum."
license     = "MIT"

srcDir = "src"

requires "nim >= 2.2.4"
requires "mummy"
requires "debby"
requires "taggy"
requires "webby"
requires "curly"
requires "chrono"
requires "crunchy"
requires "markdown"
